version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/build/
# source는 로컬의 어떤 파일들을 EC2로 옮길지에 대한 것
# destination은 로컬로부터 받아온 파일들을 EC2 instance 어디에 저장할 지에 대한 것
# 현재는 /home/ubuntu/build/ 라는 경로를 지정

hooks:
  BeforeInstall:
    - location: scripts/beforeInstall.bash
      runas: root
  AfterInstall:
    - location: scripts/afterInstall.bash
      runas: root
